favourite_channels:
  - "raw_lv"
  - "mikerics"
  # - "skima_"
  - "sidratons"
  - "imkompots"
  # - "speletlvgaming"
  # - "annnn4"
  # - "hyskeee"
  - "keen_csgo1"
  - "vadikus007"
  # - "ayrrix"
  - "kleverrlv"
  - "popazik"
  - "scvodarchives"
  - "field9"
  - "melina"
  - "nanajam777"
  - "39daph"
  # - "prelidencs"
  # - "cohhcarnage"
  # - "sodapoppin"
  - "root_supernova"
  # - "trainwreckstv"
  # - "kntent"
  - "rineksa"
  - "semmler"
  - "esl_sc2"
  - "forsen"
  # - "thageneral_r2"